package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.AbstractElementVisitor14;
import javax.lang.model.element.RecordComponentElement;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AbstractElementVisitor14}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link AbstractElementVisitor14} is a completely new class.
 * @since 14
 * @see AbstractElementVisitor14
 */
public final class WhatIsNewInAbstractElementVisitor14<R, P>
{
  /**
   * Example call to new method {@link AbstractElementVisitor14#visitRecordComponent(RecordComponentElement, Object)}.
   * @since 14
   * @see AbstractElementVisitor14#visitRecordComponent(RecordComponentElement, Object)
   */
  public R visitRecordComponent(RecordComponentElement t, P p)
  {
    AbstractElementVisitor14<R, P> testee = $$$();

    R result = testee.visitRecordComponent(t, p);
    return result;
  }

  private AbstractElementVisitor14<R, P> $$$()
  {
    return null;
  }
}
