package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.SimpleTypeVisitor14;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SimpleTypeVisitor14}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link SimpleTypeVisitor14} is a completely new class.
 * @since 14
 * @see SimpleTypeVisitor14
 */
public final class WhatIsNewInSimpleTypeVisitor14<R, P>
{
}
