package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.AbstractTypeVisitor14;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AbstractTypeVisitor14}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link AbstractTypeVisitor14} is a completely new class.
 * @since 14
 * @see AbstractTypeVisitor14
 */
public final class WhatIsNewInAbstractTypeVisitor14<R, P>
{
}
