package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.ElementKindVisitor6;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ElementKindVisitor6}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link ElementKindVisitor6} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see ElementKindVisitor6
 */
public final class WhatIsNewInElementKindVisitor6<R, P>
{
  /**
   * Example call to new method {@link ElementKindVisitor6#visitTypeAsRecord(TypeElement, Object)}.
   * @since 14
   * @see ElementKindVisitor6#visitTypeAsRecord(TypeElement, Object)
   */
  public R visitTypeAsRecord(TypeElement e, P p)
  {
    ElementKindVisitor6<R, P> testee = $$$();

    R result = testee.visitTypeAsRecord(e, p);
    return result;
  }

  /**
   * Example call to new method {@link ElementKindVisitor6#visitVariableAsBindingVariable(VariableElement, Object)}.
   * @since 14
   * @see ElementKindVisitor6#visitVariableAsBindingVariable(VariableElement, Object)
   */
  public R visitVariableAsBindingVariable(VariableElement e, P p)
  {
    ElementKindVisitor6<R, P> testee = $$$();

    R result = testee.visitVariableAsBindingVariable(e, p);
    return result;
  }

  private ElementKindVisitor6<R, P> $$$()
  {
    return null;
  }
}
