package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.Elements;
import javax.lang.model.element.RecordComponentElement;
import javax.lang.model.element.ExecutableElement;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Elements}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link Elements} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see Elements
 */
public final class WhatIsNewInElements
{
  /**
   * Example call to new method {@link Elements#recordComponentFor(ExecutableElement)}.
   * @since 14
   * @see Elements#recordComponentFor(ExecutableElement)
   */
  public RecordComponentElement recordComponentFor(ExecutableElement accessor)
  {
    Elements testee = $$$();

    RecordComponentElement result = testee.recordComponentFor(accessor);
    return result;
  }

  private Elements $$$()
  {
    return null;
  }
}
