package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.SimpleAnnotationValueVisitor14;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SimpleAnnotationValueVisitor14}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link SimpleAnnotationValueVisitor14} is a completely new class.
 * @since 14
 * @see SimpleAnnotationValueVisitor14
 */
public final class WhatIsNewInSimpleAnnotationValueVisitor14<R, P>
{
}
