package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.ElementFilter;
import java.util.List;
import javax.lang.model.element.RecordComponentElement;
import javax.lang.model.element.Element;
import java.util.Set;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ElementFilter}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link ElementFilter} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see ElementFilter
 */
public final class WhatIsNewInElementFilter
{
  /**
   * Example call to new method {@link ElementFilter#recordComponentsIn(Iterable)}.
   * @since 14
   * @see ElementFilter#recordComponentsIn(Iterable)
   */
  public static List<RecordComponentElement> recordComponentsIn(Iterable<? extends Element> elements)
  {
    List<RecordComponentElement> result = ElementFilter.recordComponentsIn(elements);
    return result;
  }

  /**
   * Example call to new method {@link ElementFilter#recordComponentsIn(Set)}.
   * @since 14
   * @see ElementFilter#recordComponentsIn(Set)
   */
  public static Set<RecordComponentElement> recordComponentsIn(Set<? extends Element> elements)
  {
    Set<RecordComponentElement> result = ElementFilter.recordComponentsIn(elements);
    return result;
  }

}
