package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.AbstractAnnotationValueVisitor14;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AbstractAnnotationValueVisitor14}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link AbstractAnnotationValueVisitor14} is a completely new class.
 * @since 14
 * @see AbstractAnnotationValueVisitor14
 */
public final class WhatIsNewInAbstractAnnotationValueVisitor14<R, P>
{
}
