package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.ElementScanner14;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.RecordComponentElement;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ElementScanner14}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link ElementScanner14} is a completely new class.
 * @since 14
 * @see ElementScanner14
 */
public final class WhatIsNewInElementScanner14<R, P>
{
  /**
   * Example call to new method {@link ElementScanner14#visitType(TypeElement, Object)}.
   * @since 14
   * @see ElementScanner14#visitType(TypeElement, Object)
   */
  public R visitType(TypeElement e, P p)
  {
    ElementScanner14<R, P> testee = $$$();

    R result = testee.visitType(e, p);
    return result;
  }

  /**
   * Example call to new method {@link ElementScanner14#visitExecutable(ExecutableElement, Object)}.
   * @since 14
   * @see ElementScanner14#visitExecutable(ExecutableElement, Object)
   */
  public R visitExecutable(ExecutableElement e, P p)
  {
    ElementScanner14<R, P> testee = $$$();

    R result = testee.visitExecutable(e, p);
    return result;
  }

  /**
   * Example call to new method {@link ElementScanner14#visitRecordComponent(RecordComponentElement, Object)}.
   * @since 14
   * @see ElementScanner14#visitRecordComponent(RecordComponentElement, Object)
   */
  public R visitRecordComponent(RecordComponentElement e, P p)
  {
    ElementScanner14<R, P> testee = $$$();

    R result = testee.visitRecordComponent(e, p);
    return result;
  }

  private ElementScanner14<R, P> $$$()
  {
    return null;
  }
}
