package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.TypeKindVisitor14;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TypeKindVisitor14}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link TypeKindVisitor14} is a completely new class.
 * @since 14
 * @see TypeKindVisitor14
 */
public final class WhatIsNewInTypeKindVisitor14<R, P>
{
}
