package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.SimpleElementVisitor14;
import javax.lang.model.element.RecordComponentElement;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SimpleElementVisitor14}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link SimpleElementVisitor14} is a completely new class.
 * @since 14
 * @see SimpleElementVisitor14
 */
public final class WhatIsNewInSimpleElementVisitor14<R, P>
{
  /**
   * Example call to new method {@link SimpleElementVisitor14#visitRecordComponent(RecordComponentElement, Object)}.
   * @since 14
   * @see SimpleElementVisitor14#visitRecordComponent(RecordComponentElement, Object)
   */
  public R visitRecordComponent(RecordComponentElement e, P p)
  {
    SimpleElementVisitor14<R, P> testee = $$$();

    R result = testee.visitRecordComponent(e, p);
    return result;
  }

  private SimpleElementVisitor14<R, P> $$$()
  {
    return null;
  }
}
