package whatisnewin.com.sun.management;

import com.sun.management.OperatingSystemMXBean;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link OperatingSystemMXBean}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link OperatingSystemMXBean} is an old class but has new fields, constructors or methods.
 * @since 1.5
 * @see OperatingSystemMXBean
 */
public final class WhatIsNewInOperatingSystemMXBean
{
  /**
   * Example call to new method {@link OperatingSystemMXBean#getFreeMemorySize()}.
   * @since 14
   * @see OperatingSystemMXBean#getFreeMemorySize()
   */
  public long getFreeMemorySize()
  {
    OperatingSystemMXBean testee = $$$();

    long result = testee.getFreeMemorySize();
    return result;
  }

  /**
   * Example call to new method {@link OperatingSystemMXBean#getTotalMemorySize()}.
   * @since 14
   * @see OperatingSystemMXBean#getTotalMemorySize()
   */
  public long getTotalMemorySize()
  {
    OperatingSystemMXBean testee = $$$();

    long result = testee.getTotalMemorySize();
    return result;
  }

  /**
   * Example call to new method {@link OperatingSystemMXBean#getCpuLoad()}.
   * @since 14
   * @see OperatingSystemMXBean#getCpuLoad()
   */
  public double getCpuLoad()
  {
    OperatingSystemMXBean testee = $$$();

    double result = testee.getCpuLoad();
    return result;
  }

  private OperatingSystemMXBean $$$()
  {
    return null;
  }
}
