package whatisnewin.java.lang.runtime;

import java.lang.runtime.ObjectMethods;
import java.lang.invoke.MethodHandles.Lookup;
import java.lang.invoke.TypeDescriptor;
import java.lang.invoke.MethodHandle;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ObjectMethods}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link ObjectMethods} is a completely new class.
 * @since 14
 * @see ObjectMethods
 */
public final class WhatIsNewInObjectMethods
{
  /**
   * Example call to new method {@link ObjectMethods#bootstrap(Lookup, String, TypeDescriptor, Class, String, MethodHandle...)}.
   * @since 14
   * @see ObjectMethods#bootstrap(Lookup, String, TypeDescriptor, Class, String, MethodHandle...)
   */
  public static Object bootstrap(Lookup lookup, String methodName, TypeDescriptor type, Class<?> recordClass, String names, MethodHandle... getters) throws Throwable
  {
    Object result = ObjectMethods.bootstrap(lookup, methodName, type, recordClass, names, getters);
    return result;
  }

}
