package whatisnewin.java.io;

import java.io.PrintStream;
import java.io.IOException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link PrintStream}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link PrintStream} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see PrintStream
 */
public final class WhatIsNewInPrintStream
{
  /**
   * Example call to new method {@link PrintStream#write(byte[])}.
   * @since 14
   * @see PrintStream#write(byte[])
   */
  public void write(byte[] buf) throws IOException
  {
    PrintStream testee = $$$();

    testee.write(buf);
  }

  /**
   * Example call to new method {@link PrintStream#writeBytes(byte[])}.
   * @since 14
   * @see PrintStream#writeBytes(byte[])
   */
  public void writeBytes(byte[] buf)
  {
    PrintStream testee = $$$();

    testee.writeBytes(buf);
  }

  private PrintStream $$$()
  {
    return null;
  }
}
