package whatisnewin.java.lang.invoke;

import java.lang.invoke.MethodHandles.Lookup;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Lookup}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link Lookup} is an old class but has new fields, constructors or methods.
 * @since 1.7
 * @see Lookup
 */
public final class WhatIsNewInMethodHandles$Lookup
{
  /**
   * Example call to new method {@link Lookup#previousLookupClass()}.
   * @since 14
   * @see Lookup#previousLookupClass()
   */
  public Class<?> previousLookupClass()
  {
    Lookup testee = $$$();

    Class<?> result = testee.previousLookupClass();
    return result;
  }

  /**
   * Example call to new method {@link Lookup#hasFullPrivilegeAccess()}.
   * @since 14
   * @see Lookup#hasFullPrivilegeAccess()
   */
  public boolean hasFullPrivilegeAccess()
  {
    Lookup testee = $$$();

    boolean result = testee.hasFullPrivilegeAccess();
    return result;
  }

  private Lookup $$$()
  {
    return null;
  }
}
