package whatisnewin.org.xml.sax;

import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ContentHandler}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link ContentHandler} is an old class but has new fields, constructors or methods.
 * @since UNDEFINED
 * @see ContentHandler
 */
public final class WhatIsNewInContentHandler
{
  /**
   * Example call to new method {@link ContentHandler#declaration(String, String, String)}.
   * @since 14
   * @see ContentHandler#declaration(String, String, String)
   */
  public void declaration(String version, String encoding, String standalone) throws SAXException
  {
    ContentHandler testee = $$$();

    testee.declaration(version, encoding, standalone);
  }

  private ContentHandler $$$()
  {
    return null;
  }
}
