package whatisnewin.java.lang;

import java.lang.reflect.RecordComponent;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Class}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link Class} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see Class
 */
public final class WhatIsNewInClass<T>
{
  /**
   * Example call to new method {@link Class#getRecordComponents()}.
   * @since 14
   * @see Class#getRecordComponents()
   */
  public RecordComponent[] getRecordComponents()
  {
    Class<T> testee = $$$();

    RecordComponent[] result = testee.getRecordComponents();
    return result;
  }

  /**
   * Example call to new method {@link Class#isRecord()}.
   * @since 14
   * @see Class#isRecord()
   */
  public boolean isRecord()
  {
    Class<T> testee = $$$();

    boolean result = testee.isRecord();
    return result;
  }

  private Class<T> $$$()
  {
    return null;
  }
}
