package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Record}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link Record} is a completely new class.
 * @since 14
 * @see Record
 */
public final class WhatIsNewInRecord
{
}
