package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link StrictMath}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link StrictMath} is an old class but has new fields, constructors or methods.
 * @since 1.3
 * @see StrictMath
 */
public final class WhatIsNewInStrictMath
{
  /**
   * Example call to new method {@link StrictMath#incrementExact(int)}.
   * @since 14
   * @see StrictMath#incrementExact(int)
   */
  public static int incrementExact(int a)
  {
    int result = StrictMath.incrementExact(a);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#incrementExact(long)}.
   * @since 14
   * @see StrictMath#incrementExact(long)
   */
  public static long incrementExact(long a)
  {
    long result = StrictMath.incrementExact(a);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#decrementExact(int)}.
   * @since 14
   * @see StrictMath#decrementExact(int)
   */
  public static int decrementExact(int a)
  {
    int result = StrictMath.decrementExact(a);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#decrementExact(long)}.
   * @since 14
   * @see StrictMath#decrementExact(long)
   */
  public static long decrementExact(long a)
  {
    long result = StrictMath.decrementExact(a);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#negateExact(int)}.
   * @since 14
   * @see StrictMath#negateExact(int)
   */
  public static int negateExact(int a)
  {
    int result = StrictMath.negateExact(a);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#negateExact(long)}.
   * @since 14
   * @see StrictMath#negateExact(long)
   */
  public static long negateExact(long a)
  {
    long result = StrictMath.negateExact(a);
    return result;
  }

}
