package whatisnewin.javax.lang.model.element;

import javax.lang.model.element.ElementKind;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ElementKind}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link ElementKind} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see ElementKind
 */
public final class WhatIsNewInElementKind
{
  /**
   * Example usage of the new field {@link ElementKind#RECORD}.
   * @since 14
   * @see ElementKind#RECORD
   */
  public static final ElementKind RECORD = ElementKind.RECORD;

  /**
   * Example usage of the new field {@link ElementKind#RECORD_COMPONENT}.
   * @since 14
   * @see ElementKind#RECORD_COMPONENT
   */
  public static final ElementKind RECORD_COMPONENT = ElementKind.RECORD_COMPONENT;

  /**
   * Example usage of the new field {@link ElementKind#BINDING_VARIABLE}.
   * @since 14
   * @see ElementKind#BINDING_VARIABLE
   */
  public static final ElementKind BINDING_VARIABLE = ElementKind.BINDING_VARIABLE;

}
