package whatisnewin.javax.lang.model.element;

import javax.lang.model.element.ElementVisitor;
import javax.lang.model.element.RecordComponentElement;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ElementVisitor}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link ElementVisitor} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see ElementVisitor
 */
public final class WhatIsNewInElementVisitor<R, P>
{
  /**
   * Example call to new method {@link ElementVisitor#visitRecordComponent(RecordComponentElement, Object)}.
   * @since 14
   * @see ElementVisitor#visitRecordComponent(RecordComponentElement, Object)
   */
  public R visitRecordComponent(RecordComponentElement e, P p)
  {
    ElementVisitor<R, P> testee = $$$();

    R result = testee.visitRecordComponent(e, p);
    return result;
  }

  private ElementVisitor<R, P> $$$()
  {
    return null;
  }
}
