package whatisnewin.javax.lang.model.element;

import javax.lang.model.element.RecordComponentElement;
import javax.lang.model.element.Element;
import javax.lang.model.element.Name;
import javax.lang.model.element.ExecutableElement;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link RecordComponentElement}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link RecordComponentElement} is a completely new class.
 * @since 14
 * @see RecordComponentElement
 */
public final class WhatIsNewInRecordComponentElement
{
  /**
   * Example call to new method {@link RecordComponentElement#getEnclosingElement()}.
   * @since 14
   * @see RecordComponentElement#getEnclosingElement()
   */
  public Element getEnclosingElement()
  {
    RecordComponentElement testee = $$$();

    Element result = testee.getEnclosingElement();
    return result;
  }

  /**
   * Example call to new method {@link RecordComponentElement#getSimpleName()}.
   * @since 14
   * @see RecordComponentElement#getSimpleName()
   */
  public Name getSimpleName()
  {
    RecordComponentElement testee = $$$();

    Name result = testee.getSimpleName();
    return result;
  }

  /**
   * Example call to new method {@link RecordComponentElement#getAccessor()}.
   * @since 14
   * @see RecordComponentElement#getAccessor()
   */
  public ExecutableElement getAccessor()
  {
    RecordComponentElement testee = $$$();

    ExecutableElement result = testee.getAccessor();
    return result;
  }

  private RecordComponentElement $$$()
  {
    return null;
  }
}
