package whatisnewin.javax.lang.model.element;

import javax.lang.model.element.TypeElement;
import java.util.List;
import javax.lang.model.element.RecordComponentElement;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TypeElement}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link TypeElement} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see TypeElement
 */
public final class WhatIsNewInTypeElement
{
  /**
   * Example call to new method {@link TypeElement#getRecordComponents()}.
   * @since 14
   * @see TypeElement#getRecordComponents()
   */
  public List<? extends RecordComponentElement> getRecordComponents()
  {
    TypeElement testee = $$$();

    List<? extends RecordComponentElement> result = testee.getRecordComponents();
    return result;
  }

  private TypeElement $$$()
  {
    return null;
  }
}
