package whatisnewin.java.util.concurrent.locks;

import java.util.concurrent.locks.LockSupport;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link LockSupport}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link LockSupport} is an old class but has new fields, constructors or methods.
 * @since 1.5
 * @see LockSupport
 */
public final class WhatIsNewInLockSupport
{
  /**
   * Example call to new method {@link LockSupport#setCurrentBlocker(Object)}.
   * @since 14
   * @see LockSupport#setCurrentBlocker(Object)
   */
  public static void setCurrentBlocker(Object blocker)
  {
    LockSupport.setCurrentBlocker(blocker);
  }

}
