package whatisnewin.jdk.jfr.consumer;

import jdk.jfr.consumer.RecordingStream;
import jdk.jfr.Configuration;
import jdk.jfr.EventSettings;
import java.util.Map;
import jdk.jfr.Event;
import java.time.Duration;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link RecordingStream}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link RecordingStream} is a completely new class.
 * @since 14
 * @see RecordingStream
 */
public final class WhatIsNewInRecordingStream
{
  /**
   * Example call to new constructor {@link RecordingStream#RecordingStream()}.
   * @since 14
   * @see RecordingStream#RecordingStream()
   */
  public WhatIsNewInRecordingStream()
  {
    RecordingStream testee = new RecordingStream();
  }

  /**
   * Example call to new constructor {@link RecordingStream#RecordingStream(Configuration)}.
   * @since 14
   * @see RecordingStream#RecordingStream(Configuration)
   */
  public WhatIsNewInRecordingStream(Configuration configuration)
  {
    RecordingStream testee = new RecordingStream(configuration);
  }

  /**
   * Example call to new method {@link RecordingStream#enable(String)}.
   * @since 14
   * @see RecordingStream#enable(String)
   */
  public EventSettings enable(String name)
  {
    RecordingStream testee = $$$();

    EventSettings result = testee.enable(name);
    return result;
  }

  /**
   * Example call to new method {@link RecordingStream#setSettings(Map)}.
   * @since 14
   * @see RecordingStream#setSettings(Map)
   */
  public void setSettings(Map<String, String> settings)
  {
    RecordingStream testee = $$$();

    testee.setSettings(settings);
  }

  /**
   * Example call to new method {@link RecordingStream#enable(Class)}.
   * @since 14
   * @see RecordingStream#enable(Class)
   */
  public EventSettings enable(Class<? extends Event> eventClass)
  {
    RecordingStream testee = $$$();

    EventSettings result = testee.enable(eventClass);
    return result;
  }

  /**
   * Example call to new method {@link RecordingStream#disable(String)}.
   * @since 14
   * @see RecordingStream#disable(String)
   */
  public EventSettings disable(String name)
  {
    RecordingStream testee = $$$();

    EventSettings result = testee.disable(name);
    return result;
  }

  /**
   * Example call to new method {@link RecordingStream#disable(Class)}.
   * @since 14
   * @see RecordingStream#disable(Class)
   */
  public EventSettings disable(Class<? extends Event> eventClass)
  {
    RecordingStream testee = $$$();

    EventSettings result = testee.disable(eventClass);
    return result;
  }

  /**
   * Example call to new method {@link RecordingStream#setMaxAge(Duration)}.
   * @since 14
   * @see RecordingStream#setMaxAge(Duration)
   */
  public void setMaxAge(Duration maxAge)
  {
    RecordingStream testee = $$$();

    testee.setMaxAge(maxAge);
  }

  /**
   * Example call to new method {@link RecordingStream#setMaxSize(long)}.
   * @since 14
   * @see RecordingStream#setMaxSize(long)
   */
  public void setMaxSize(long maxSize)
  {
    RecordingStream testee = $$$();

    testee.setMaxSize(maxSize);
  }

  private RecordingStream $$$()
  {
    return null;
  }
}
