package whatisnewin.jdk.jfr.consumer;

import jdk.jfr.consumer.EventStream;
import java.io.IOException;
import java.nio.file.Path;
import java.util.function.Consumer;
import jdk.jfr.consumer.RecordedEvent;
import java.time.Instant;
import java.time.Duration;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link EventStream}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link EventStream} is a completely new class.
 * @since 14
 * @see EventStream
 */
public final class WhatIsNewInEventStream
{
  /**
   * Example call to new method {@link EventStream#openRepository()}.
   * @since 14
   * @see EventStream#openRepository()
   */
  public static EventStream openRepository() throws IOException
  {
    EventStream result = EventStream.openRepository();
    return result;
  }

  /**
   * Example call to new method {@link EventStream#openRepository(Path)}.
   * @since 14
   * @see EventStream#openRepository(Path)
   */
  public static EventStream openRepository(Path directory) throws IOException
  {
    EventStream result = EventStream.openRepository(directory);
    return result;
  }

  /**
   * Example call to new method {@link EventStream#openFile(Path)}.
   * @since 14
   * @see EventStream#openFile(Path)
   */
  public static EventStream openFile(Path file) throws IOException
  {
    EventStream result = EventStream.openFile(file);
    return result;
  }

  /**
   * Example call to new method {@link EventStream#onEvent(Consumer)}.
   * @since 14
   * @see EventStream#onEvent(Consumer)
   */
  public void onEvent(Consumer<RecordedEvent> action)
  {
    EventStream testee = $$$();

    testee.onEvent(action);
  }

  /**
   * Example call to new method {@link EventStream#onEvent(String, Consumer)}.
   * @since 14
   * @see EventStream#onEvent(String, Consumer)
   */
  public void onEvent(String eventName, Consumer<RecordedEvent> action)
  {
    EventStream testee = $$$();

    testee.onEvent(eventName, action);
  }

  /**
   * Example call to new method {@link EventStream#onFlush(Runnable)}.
   * @since 14
   * @see EventStream#onFlush(Runnable)
   */
  public void onFlush(Runnable action)
  {
    EventStream testee = $$$();

    testee.onFlush(action);
  }

  /**
   * Example call to new method {@link EventStream#onError(Consumer)}.
   * @since 14
   * @see EventStream#onError(Consumer)
   */
  public void onError(Consumer<Throwable> action)
  {
    EventStream testee = $$$();

    testee.onError(action);
  }

  /**
   * Example call to new method {@link EventStream#onClose(Runnable)}.
   * @since 14
   * @see EventStream#onClose(Runnable)
   */
  public void onClose(Runnable action)
  {
    EventStream testee = $$$();

    testee.onClose(action);
  }

  /**
   * Example call to new method {@link EventStream#close()}.
   * @since 14
   * @see EventStream#close()
   */
  public void close()
  {
    EventStream testee = $$$();

    testee.close();
  }

  /**
   * Example call to new method {@link EventStream#remove(Object)}.
   * @since 14
   * @see EventStream#remove(Object)
   */
  public boolean remove(Object action)
  {
    EventStream testee = $$$();

    boolean result = testee.remove(action);
    return result;
  }

  /**
   * Example call to new method {@link EventStream#setReuse(boolean)}.
   * @since 14
   * @see EventStream#setReuse(boolean)
   */
  public void setReuse(boolean reuse)
  {
    EventStream testee = $$$();

    testee.setReuse(reuse);
  }

  /**
   * Example call to new method {@link EventStream#setOrdered(boolean)}.
   * @since 14
   * @see EventStream#setOrdered(boolean)
   */
  public void setOrdered(boolean ordered)
  {
    EventStream testee = $$$();

    testee.setOrdered(ordered);
  }

  /**
   * Example call to new method {@link EventStream#setStartTime(Instant)}.
   * @since 14
   * @see EventStream#setStartTime(Instant)
   */
  public void setStartTime(Instant startTime)
  {
    EventStream testee = $$$();

    testee.setStartTime(startTime);
  }

  /**
   * Example call to new method {@link EventStream#setEndTime(Instant)}.
   * @since 14
   * @see EventStream#setEndTime(Instant)
   */
  public void setEndTime(Instant endTime)
  {
    EventStream testee = $$$();

    testee.setEndTime(endTime);
  }

  /**
   * Example call to new method {@link EventStream#start()}.
   * @since 14
   * @see EventStream#start()
   */
  public void start()
  {
    EventStream testee = $$$();

    testee.start();
  }

  /**
   * Example call to new method {@link EventStream#startAsync()}.
   * @since 14
   * @see EventStream#startAsync()
   */
  public void startAsync()
  {
    EventStream testee = $$$();

    testee.startAsync();
  }

  /**
   * Example call to new method {@link EventStream#awaitTermination(Duration)}.
   * @since 14
   * @see EventStream#awaitTermination(Duration)
   */
  public void awaitTermination(Duration timeout) throws InterruptedException
  {
    EventStream testee = $$$();

    testee.awaitTermination(timeout);
  }

  /**
   * Example call to new method {@link EventStream#awaitTermination()}.
   * @since 14
   * @see EventStream#awaitTermination()
   */
  public void awaitTermination() throws InterruptedException
  {
    EventStream testee = $$$();

    testee.awaitTermination();
  }

  private EventStream $$$()
  {
    return null;
  }
}
