package whatisnewin.jdk.jshell;

import jdk.jshell.Snippet.SubKind;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SubKind}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link SubKind} is an old class but has new fields, constructors or methods.
 * @since 9
 * @see SubKind
 */
public final class WhatIsNewInSnippet$SubKind
{
  /**
   * Example usage of the new field {@link SubKind#RECORD_SUBKIND}.
   * @since 14
   * @see SubKind#RECORD_SUBKIND
   */
  public static final SubKind RECORD_SUBKIND = SubKind.RECORD_SUBKIND;

}
