package whatisnewin.com.sun.source.util;

import com.sun.source.util.TreeScanner;
import com.sun.source.tree.BindingPatternTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TreeScanner}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link TreeScanner} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see TreeScanner
 */
public final class WhatIsNewInTreeScanner<R, P>
{
  /**
   * Example call to new method {@link TreeScanner#visitBindingPattern(BindingPatternTree, Object)}.
   * @since 14
   * @see TreeScanner#visitBindingPattern(BindingPatternTree, Object)
   */
  public R visitBindingPattern(BindingPatternTree node, P p)
  {
    TreeScanner<R, P> testee = $$$();

    R result = testee.visitBindingPattern(node, p);
    return result;
  }

  private TreeScanner<R, P> $$$()
  {
    return null;
  }
}
