package whatisnewin.com.sun.source.util;

import com.sun.source.util.SimpleTreeVisitor;
import com.sun.source.tree.BindingPatternTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SimpleTreeVisitor}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link SimpleTreeVisitor} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see SimpleTreeVisitor
 */
public final class WhatIsNewInSimpleTreeVisitor<R, P>
{
  /**
   * Example call to new method {@link SimpleTreeVisitor#visitBindingPattern(BindingPatternTree, Object)}.
   * @since 14
   * @see SimpleTreeVisitor#visitBindingPattern(BindingPatternTree, Object)
   */
  public R visitBindingPattern(BindingPatternTree node, P p)
  {
    SimpleTreeVisitor<R, P> testee = $$$();

    R result = testee.visitBindingPattern(node, p);
    return result;
  }

  private SimpleTreeVisitor<R, P> $$$()
  {
    return null;
  }
}
