package whatisnewin.java.lang.reflect;

import java.lang.reflect.RecordComponent;
import java.lang.reflect.Type;
import java.lang.reflect.AnnotatedType;
import java.lang.reflect.Method;
import java.lang.annotation.Annotation;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link RecordComponent}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link RecordComponent} is a completely new class.
 * @since 14
 * @see RecordComponent
 */
public final class WhatIsNewInRecordComponent
{
  /**
   * Example call to new method {@link RecordComponent#getName()}.
   * @since 14
   * @see RecordComponent#getName()
   */
  public String getName()
  {
    RecordComponent testee = $$$();

    String result = testee.getName();
    return result;
  }

  /**
   * Example call to new method {@link RecordComponent#getType()}.
   * @since 14
   * @see RecordComponent#getType()
   */
  public Class<?> getType()
  {
    RecordComponent testee = $$$();

    Class<?> result = testee.getType();
    return result;
  }

  /**
   * Example call to new method {@link RecordComponent#getGenericSignature()}.
   * @since 14
   * @see RecordComponent#getGenericSignature()
   */
  public String getGenericSignature()
  {
    RecordComponent testee = $$$();

    String result = testee.getGenericSignature();
    return result;
  }

  /**
   * Example call to new method {@link RecordComponent#getGenericType()}.
   * @since 14
   * @see RecordComponent#getGenericType()
   */
  public Type getGenericType()
  {
    RecordComponent testee = $$$();

    Type result = testee.getGenericType();
    return result;
  }

  /**
   * Example call to new method {@link RecordComponent#getAnnotatedType()}.
   * @since 14
   * @see RecordComponent#getAnnotatedType()
   */
  public AnnotatedType getAnnotatedType()
  {
    RecordComponent testee = $$$();

    AnnotatedType result = testee.getAnnotatedType();
    return result;
  }

  /**
   * Example call to new method {@link RecordComponent#getAccessor()}.
   * @since 14
   * @see RecordComponent#getAccessor()
   */
  public Method getAccessor()
  {
    RecordComponent testee = $$$();

    Method result = testee.getAccessor();
    return result;
  }

  /**
   * Example call to new method {@link RecordComponent#getAnnotation(Class)}.
   * @since 14
   * @see RecordComponent#getAnnotation(Class)
   */
  public <T extends Annotation> T getAnnotation(Class<T> annotationClass)
  {
    RecordComponent testee = $$$();

    T result = testee.getAnnotation(annotationClass);
    return result;
  }

  /**
   * Example call to new method {@link RecordComponent#getDeclaringRecord()}.
   * @since 14
   * @see RecordComponent#getDeclaringRecord()
   */
  public Class<?> getDeclaringRecord()
  {
    RecordComponent testee = $$$();

    Class<?> result = testee.getDeclaringRecord();
    return result;
  }

  private RecordComponent $$$()
  {
    return null;
  }
}
