package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.Tree.Kind;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Kind}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link Kind} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see Kind
 */
public final class WhatIsNewInTree$Kind
{
  /**
   * Example usage of the new field {@link Kind#BINDING_PATTERN}.
   * @since 14
   * @see Kind#BINDING_PATTERN
   */
  public static final Kind BINDING_PATTERN = Kind.BINDING_PATTERN;

  /**
   * Example usage of the new field {@link Kind#RECORD}.
   * @since 14
   * @see Kind#RECORD
   */
  public static final Kind RECORD = Kind.RECORD;

}
