package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.BindingPatternTree;
import com.sun.source.tree.Tree;
import javax.lang.model.element.Name;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link BindingPatternTree}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link BindingPatternTree} is a completely new class.
 * @since 14
 * @see BindingPatternTree
 */
public final class WhatIsNewInBindingPatternTree
{
  /**
   * Example call to new method {@link BindingPatternTree#getType()}.
   * @since 14
   * @see BindingPatternTree#getType()
   */
  public Tree getType()
  {
    BindingPatternTree testee = $$$();

    Tree result = testee.getType();
    return result;
  }

  /**
   * Example call to new method {@link BindingPatternTree#getBinding()}.
   * @since 14
   * @see BindingPatternTree#getBinding()
   */
  public Name getBinding()
  {
    BindingPatternTree testee = $$$();

    Name result = testee.getBinding();
    return result;
  }

  private BindingPatternTree $$$()
  {
    return null;
  }
}
