package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.InstanceOfTree;
import com.sun.source.tree.PatternTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link InstanceOfTree}
 * that were newly introduced in Java version 14.<br>
 *
 * {@link InstanceOfTree} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see InstanceOfTree
 */
public final class WhatIsNewInInstanceOfTree
{
  /**
   * Example call to new method {@link InstanceOfTree#getPattern()}.
   * @since 14
   * @see InstanceOfTree#getPattern()
   */
  public PatternTree getPattern()
  {
    InstanceOfTree testee = $$$();

    PatternTree result = testee.getPattern();
    return result;
  }

  private InstanceOfTree $$$()
  {
    return null;
  }
}
